language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential unzip cmake mercurial uuid-dev libcurl4-openssl-dev liblua5.1-0-dev libgtest-dev libpng-dev libsqlite3-dev libssl-dev zlib1g-dev libdcmtk2-dev libwrap0-dev libcharls-dev

# Travis-CI uses Ubuntu 12.04 virtual machines, with Boost 1.46.0
# (whereas Orthanc expects Boost >= 1.48.0)
script: ./Resources/TravisUbuntu-12.04.sh
